### ISSUE TITLE
ERROR: Failed building wheel for pillow

### ISSUE THREAD

**Issue by nelsonleedemo** [computationalcore/cryptosteganography#11]
**Describe the bug**
Cannot install, and get ERROR: Failed building wheel for pillow

**To Reproduce**
1. Simply running "pip3 install cryptosteganography"

**Additional context**
Default python installed
- python 3.9.9
- python 2.7.18

OS: macOS

**Comment by computationalcore** [comment]
@nelsonleedemo thanks for reporting, I will check that and fix it in a few days.
